openapi: 3.0.3
info:
  title: Job Listing API service
  version: 1.0.0
  description: This project provides an API service for building Job Listing Platforms,
    by providing needed functionalities and security
paths:
  /api/v1/login/:
    post:
      operationId: v1_login_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/v1/logout/:
    post:
      operationId: v1_logout_create
      description: logs out currently logged in user
      tags:
      - v1
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/register/:
    post:
      operationId: v1_register_create
      description: |-
        receives the user registration credentials for and registers the user
        if the credentials are validated
      tags:
      - v1
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/token/refresh/:
    post:
      operationId: v1_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1change-password/:
    put:
      operationId: v1change_password_update
      description: |-
        changes the password of authenticated users by providing
        current password
      tags:
      - v1change-password
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1current-user/:
    get:
      operationId: v1current_user_retrieve
      description: returns currently authenticated users
      tags:
      - v1current-user
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/v1delete-post/{id}/:
    delete:
      operationId: v1delete_post_destroy
      description: deletes seleted post by the author
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1delete-post
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/v1job-applications/:
    post:
      operationId: v1job_applications_create
      description: |-
        Receives job application credentials from applicants
        and saves to the database, to be accessible by the job posters
      tags:
      - v1job-applications
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/v1job-listings/:
    get:
      operationId: v1job_listings_retrieve
      description: |-
        returns list of available jobs sorted in descending order
        based on date posted
      tags:
      - v1job-listings
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1logout/:
    post:
      operationId: v1logout_create
      description: logs out currently logged in user
      tags:
      - v1logout
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1update-profile/:
    patch:
      operationId: v1update_profile_partial_update
      description: accepts user data for profile modifications
      tags:
      - v1update-profile
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    TokenObtainPair:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - email
      - password
      - refresh
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
