# Generated by Django 5.1.1 on 2024-11-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
